<a href="https://colab.research.google.com/github/akshaypradheep/Python-Intermediate-Course-by-Wioo/blob/master/Assignment_Day01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#1. Give two 1D Matrices and find the sum of its BIGGEST elements 
import numpy as np
a=np.array([1,10,5,2,4,3,8])
b=np.array([10,3,5,2,5,9,4])
print((np.sort(a)[-1])+(np.sort(a)[-1]))

20


In [43]:
#2.Give two 2D Matrices A and B, Find the Big of Smallest elements from A and B
import numpy as np
a=np.array([[10,20,30,40,50],[1,2,3,4,5]])
b=np.array([[60,70,80,90,100],[6,7,8,9,10]])
#c=np.array([np.sort(a.ravel())[0],np.sort(b.ravel())[0]])
c=np.array([np.amin(a),np.amin(b)])
print(np.amax(c))

6


In [63]:
#  3.Give 2 2D matrices A & B,convert both to its flattened representations 
#say C & D, find sum matrix (E) of C & D, display the transpose of matrix E
import numpy as np
a=np.array([[10,20,30,40,50],[1,2,3,4,5]])
b=np.array([[60,70,80,90,100],[6,7,8,9,10]])
c=np.ravel(a)
d=np.ravel(b)
e=c+d
print(e.T)

[ 70  90 110 130 150   7   9  11  13  15]


In [84]:
#4. Perform matrix multiplication of a 3x4 and 4x5 matrix
import numpy as np
a=np.arange(1,13,1).reshape(3,4)
b=np.arange(1,21,1).reshape(4,5)
print(np.dot(a,b))

[[110 120 130 140 150]
 [246 272 298 324 350]
 [382 424 466 508 550]]


In [89]:
#5.Reverse a 1D array, and perform sorting on it 
import numpy as np
a=np.array([3,2,4,1,6,7,9,8,5])
print("array in reverse",a[::-1])
print("sorted array",np.sort(a[::-1]))


array in reverse [5 8 9 7 6 1 4 2 3]
sorted array [1 2 3 4 5 6 7 8 9]
