<a href="https://colab.research.google.com/github/akshaypradheep/Python-Intermediate-Course-by-Wioo/blob/master/pythonIntermediate_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
#one dimensional Array
a=np.array([5,3,5,3,2,1,4])
print(a)


[5 3 5 3 2 1 4]


In [13]:
#2d array
import numpy as np
b=np.array([[1,2,3,4,5],[9,6,5,4,4]])
print(b)
print(b[1][1])

[[1 2 3 4 5]
 [9 6 5 4 4]]
6


In [16]:
#array operation
#search,sum,sum of 2 arrays,big of array, small of array,sort, traversal 

a=np.array([10,20,30,40,50])
a=a+1
print(a)

[11 21 31 41 51]


In [21]:
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])
c=a%b
print(c)

[0 0 0 0 0]


In [26]:
#create array of of zeros and ones
a=np.zeros(3)
b=np.ones(2)
c=np.zeros((2,2))
print(a)
print(b)
print(c)

[0. 0. 0.]
[1. 1.]
[[0. 0.]
 [0. 0.]]


In [30]:
#logical operation < , > ,==
a=np.array([1,2,3,4,12])
b=np.array([2,3,4,5,12])
a==b
#a<b



array([ True,  True,  True,  True, False])

In [33]:
#logical operations
a=np.array([2,3,4])
b=np.array([2,3,4])
np.logical_or(a,b)

array([ True,  True,  True])

In [38]:
#sum of total elements in the array
a=np.array([[1,2,3,4],[10,2,3,4]])
print("sum of total elements :", np.sum(a))

sum of total elements : 29


In [52]:
#sum of row || coloum only 
a=np.array([[10,20,30,40,50],[1,2,3,4,5]])
print("row sum =",a.sum(axis=1))
print("row column sum =",a.sum(axis=0))
np.sum(a,axis=1) #axis 1=row, 0=colun


row sum = [150  15]
row column sum = [11 22 33 44 55]


array([150,  15])

In [53]:
#transpose
a=np.array([[10,20,30,40,50],[1,2,3,4,5]])
print(a.T)

[[10  1]
 [20  2]
 [30  3]
 [40  4]
 [50  5]]


In [57]:
#Flatten
a=np.array([[10,20,30,40,50],[1,2,3,4,5]])
b=a.ravel()
print(b)
print(a.T.ravel())

[10 20 30 40 50  1  2  3  4  5]
[10  1 20  2 30  3 40  4 50  5]


In [62]:
#sorting
a=np.array([[50,10,40,30,50],[2,3,1,5,4]])
a.sort()
print(a)

[[10 30 40 50 50]
 [ 1  2  3  4  5]]


In [65]:
#sorting row colum wise
a=np.array([[50,10,40,30,50],[2,3,1,5,4]])
a.sort(axis=0)
print(a)

[[ 2  3  1  5  4]
 [50 10 40 30 50]]


In [77]:
#slicing
a=np.array([[50,10,40,30,50],[2,3,1,5,4]])
print(a[0][0:3])

[50 10 40]


In [81]:
a=np.array([[3,4,5,6,7],
            [9,8,7,6,5]])
b=np.array([[1,1,1,1,1],
            [1,1,1,1,1]])
np.multiply(a,b)


array([[3, 4, 5, 6, 7],
       [9, 8, 7, 6, 5]])